export default {
  START_WISHLISTGROUP: 'START_WISHLISTGROUP',
  FETCH_WISHLISTGROUP: 'FETCH_WISHLISTGROUP',
  COMPLETE_WISHLISTGROUP: 'ADD_COMPLETE_WISHLISTGROUP',
  FAILED_WISHLISTGROUP: 'ADD_FAILED_WISHLISTGROUP',
};
