export default {
  FETCH_CART: 'FETCH_CART',
  START_CART_LOADING: 'START_CART_LOADING',
  FINISH_CART_LOADING: 'FINISH_CART_LOADING',
  START_CART_ITEM_LOADING: 'START_CART_ITEM_LOADING',
  FINISH_CART_ITEM_LOADING: 'FINISH_CART_ITEM_LOADING',
  FINISH_REORDER: 'FINISH_REORDER',
  APPLY_COUPON_ERROR: 'APPLY_COUPON_ERROR',
  FETCH_GIFT_WRAPPING: 'FETCH_GIFT_WRAPPING',
  START_PUT_LOADING: 'START_PUT_LOADING',
  FINISH_PUT_LOADING: 'FINISH_PUT_LOADING',
  HANDLE_ALERT_INFO_COUPON_CODE: 'HANDLE_ALERT_INFO_COUPON_CODE',
};
