export default {
  FETCH_THE1CARD: 'FETCH_THE1CARD',
  START_LOGIN_T1C_LOADING: 'START_LOGIN_T1C_LOADING',
  STOP_LOGIN_T1C_LOADING: 'STOP_LOGIN_T1C_LOADING',
  START_LOADING_REDEEM_T1: 'START_LOADING_REDEEM_T1',
  STOP_LOADING_REDEEM_T1: 'STOP_LOADING_REDEEM_T1',
  STOP_LOADING_REMOVE_REDEEM_T1: 'STOP_LOADING_REMOVE_REDEEM_T1',
};
