export default {
  PRODUCT_SIMPLE: 'product_simple',
  PRODUCT_CONFIGURABLE: 'product_configurable',
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub_category',
  SEARCH: 'search',
  HOME: 'home',
  CHECKOUT: 'checkout',
  PAYMENT: 'payment',
  CART: 'cart',
  ORDER_COMPLETE: 'order_complete',
  LAYOUT: 'layout',
  CONTENT: 'content',
  BRAND: 'brand',
  BRAND_BOUTIQUE: 'brand_boutique',
  ACCOUNT: 'account',
  REGISTER: 'register',
  INFORMATION: 'information',
  OTHER: 'other',

  // Even Tracking Name
  EVENT_TRACK_PROMOTION_CLICK: 'js-trackPromo',
  EVENT_TRACK_PRODUCT_CLICK: 'js-trackProductClick',
  EVENT_TRACK_PRODUCT_IMPRESSION: 'js-trackProductImpression',
  EVENT_TRACK_ADD_TO_CART: 'js-trackAddToCart',
  EVENT_TRACK_REMOVE_FROM_CART: 'js-trackRemoveFromCart',
  EVENT_CHECKOUT_STEP_ONE: 'js-trackCheckoutStepone',
  EVENT_CHECKOUT_STEP_TWO: 'js-trackCheckoutSteptwo',
  EVENT_CHECKOUT_STEP_THREE: 'js-trackCheckoutStepthree',
  EVENT_ADD_TO_WISHLIST: 'js-addToWishList',
  EVENT_CLEAR_BATH: 'clear-bath',
};
