export default {
  LOAD_ORDER_HISTORY: 'LOAD_ORDER_HISTORY',
  ORDER_FETCH_FAILED: 'ORDER_FETCH_FAILED',
  FETCH_ORDER: 'FETCH_ORDER',
  LOADING_ORDER: 'LOADING_ORDER',
  STOP_LOADING_ORDER: 'STOP_LOADING_ORDER',
  PUSH_ORDER: 'PUSH_ORDER',
  LOAD_ORDER_HISTORY_LATEST: 'LOAD_ORDER_HISTORY_LATEST',
};
