export const OPEN_LOGIN_DESKTOP = 'OPEN_LOGIN_DESKTOP';
export const CLOSE_LOGIN_DESKTOP = 'CLOSE_LOGIN_DESKTOP';
export const SET_POPUP_ADD_TO_CART = 'SET_POPUP_ADD_TO_CART';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
