export default {
  BILLING_FETCHING_ADDRESS_DATA_SUCCESS: 'BILLING_FETCH_ADDRESS_DATA_SUCCESS',
  BILLING_FETCHING_ADDRESS_DATA_FAILED: 'BILLING_FETCH_ADDRESS_DATA_FAILED',
  BILLING_FETCHING_ADDRESS_FAILED: 'BILLING_FETCHING_ADDRESS_FAILED',
  BILLING_FETCHING_ADDRESSES_FAILED: 'BILLING_FETCHING_ADDRESSES_FAILED',
  BILLING_FETCHING_REGION_SUCCESS: 'BILLING_FETCHING_REGION_SUCCESS',
  BILLING_FETCHING_DISTRICT_SUCCESS: 'BILLING_FETCHING_DISTRICT_SUCCESS',
  BILLING_FETCHING_SUB_DISTRICT_SUCCESS:
    'BILLING_FETCHING_SUB_DISTRICT_SUCCESS',
  BILLING_BY_POSTCODE_SUCCESS: 'BILLING_BY_POSTCODE_SUCCESS',
  BILLING_BY_POSTCODE_FAIL: 'BILLING_BY_POSTCODE_FAIL',
  BILLING_BY_POSTCODE_START: 'BILLING_BY_POSTCODE_START',
};
