export default {
  'x-product-attr': [
    'free_delivery',
    'free_text_flag',
    'badge',
    'show_badge',
    'free_installation',
    'product_tags',
    'related_to',
    'home_branch',
    'attached_pdf_file',
    'model',
    'barcode',
    'click_collect',
    'shipping_methods',
    'payment_methods',
    'flash_deal_enable',
    'special_to_date',
    'special_from_date',
    'new',
    'promo_name_tag',
    'brand_model',
    'size_type',
    'size',
    'product_size_simple',
    'product_tags',
  ],
  'x-product-attr-option': [
    'brand',
    'is_returnable',
    'price_discount',
    'brand_name',
    'product_size_simple',
  ],
};
