export default {
  FETCH_ACCOUNT_INFORMATION: 'FETCH_ACCOUNT_INFORMATION',
  FETCH_ACCOUNT_INFORMATION_ERROR: 'FETCH_ACCOUNT_INFORMATION_ERROR',
  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_END: 'UPDATE_PROFILE_END',
};
