export default {
  FETCH_PAYMENT: 'FETCH_PAYMENT',
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
  SET_PAY_123: 'SET_PAY_123',
  SET_PAY_IPP: 'SET_PAY_IPP',
  SET_PAYMENT_EWALLET_METHOD: 'SET_PAYMENT_EWALLET_METHOD',
  START_ONTOP_CREDITCARD: 'START_ONTOP_CREDITCARD',
  STOP_ONTOP_CREDITCARD: 'STOP_ONTOP_CREDITCARD',
  SET_ONTOP_CREDITCARD: 'SET_ONTOP_CREDITCARD',
  START_FETCH_PAYMENT_METHOD: 'START_FETCH_PAYMENT_METHOD',
  END_FETCH_PAYMENT_METHOD: 'END_FETCH_PAYMENT_METHOD',
  CLEAR_EXTENSION: 'CLEAR_EXTENSION',
};
