export default {
  OPEN_MOBILE_MENU: 'OPEN_MOBILE_MENU',
  CLOSE_MOBILE_MENU: 'CLOSE_MOBILE_MENU',
  OPEN_MOBILE_MODAL: 'OPEN_MOBILE_MODAL',
  CLOSE_MOBILE_MODAL: 'CLOSE_MOBILE_MODAL',
  SHOW_MOBILE_SEARCH: 'SHOW_MOBILE_SEARCH',
  HIDE_MOBILE_SEARCH: 'HIDE_MOBILE_SEARCH',
  OPEN_ALERT: 'OPEN_ALERT',
  CLOSE_ALERT: 'CLOSE_ALERT',
  HIDE_MEGAMENU_START: 'HIDE_MEGAMENU_START',
  HIDE_MEGAMENU_END: 'HIDE_MEGAMENU_END',
  SHOW_MINI_CART: 'SHOW_MINI_CART',
  HIDE_MINI_CART: 'HIDE_MINI_CART',
};
