export default {
  FETCH_CUSTOMER: 'FETCH_CUSTOMER',
  CHANGE_CUSTOMER_TYPE: 'CHANGE_CUSTOMER_TYPE',
  SET_PASSWORD_CHANGE_MESSAGE: 'SET_PASSWORD_CHANGE_MESSAGE',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  UPDATE_CUSTOMER_COMPLETED: 'UPDATE_CUSTOMER_COMPLETED',
};
