export default {
  //register
  REGISTER_SEND: 'REGISTER_SEND',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  //login
  LOGIN_SEND: 'LOGIN_SEND',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  //forgot password
  FORGOT_START: 'FORGOT_START',
  FORGOT_SUCCESS: 'FORGOT_SUCCESS',
  FORGOT_FAILED: 'FORGOT_FAILED',

  //reset password
  RESET_PASSWORD_SEND: 'RESET_PASSWORD_SEND',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
};
